# Shared by scripts/agent-run and scripts/agent-status: Quadlet unit naming,
# rendering, and the systemd-state-to-outcome mapping. Pure functions only
# (stdout in, stdout out; the two systemctl calls are confined to
# agent_unit_active and agent_unit_props), so scripts/agent-run.test.sh can
# source this file and check it without podman or a systemd --user session.
#
# Placement: $XDG_RUNTIME_DIR/containers/systemd/, not the persistent
# $XDG_CONFIG_HOME one. Quadlet documents the runtime-dir path as the one for
# temporary units; a run's unit belongs there since agent-run deletes it
# itself once the run ends, and a crash before cleanup still self-clears at
# the next reboot instead of accumulating in persistent config.

quadlet_dir() {
    printf '%s/containers/systemd\n' "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
}

quadlet_unit() { # <id> -> unit name, without .container/.service
    printf 'agent-%s\n' "$1"
}

# Renders the .container Quadlet unit for one run to stdout.
#
# Volumes/environment/secret are passed pre-built (one directive per line, or
# empty) since what they contain depends on the harness and on agent-run's
# own environment, which this function does not read. Memory, CPU and tasks
# are systemd resource control, not Podman flags: RuntimeMaxSec is what makes
# the wall-time deadline a systemd job rather than something agent-run
# polls for.
render_agent_unit() { # <id> <image> <exec> <volumes> <environment> <secret> <cpu-quota-pct> <deadline-sec> <stop-grace-sec>
    id=$1 image=$2 exec=$3 volumes=$4 environment=$5 secret=$6 cpu_quota=$7 deadline=$8 stop_grace=$9
    printf '# Generated by scripts/agent-run for run %s; do not edit by hand.\n' "$id"
    printf '[Unit]\n'
    printf 'Description=agent sandbox run %s\n' "$id"
    printf '\n[Container]\n'
    printf 'Image=%s\n' "$image"
    printf 'Pull=never\n'
    printf 'ContainerName=%s\n' "$(quadlet_unit "$id")"
    printf 'UserNS=keep-id\n'
    printf '%s\n' "$volumes"
    [ -n "$environment" ] && printf '%s\n' "$environment"
    [ -n "$secret" ] && printf '%s\n' "$secret"
    printf 'Exec=%s\n' "$exec"
    printf '\n[Service]\n'
    # No automatic restart: a failed or timed-out run is not retried.
    printf 'Restart=no\n'
    printf 'MemoryMax=16G\n'
    printf 'CPUQuota=%s%%\n' "$cpu_quota"
    printf 'TasksMax=4096\n'
    printf 'RuntimeMaxSec=%s\n' "$deadline"
    printf 'TimeoutStopSec=%s\n' "$stop_grace"
    printf 'OOMPolicy=kill\n'
}

# True if the run's unit is currently active (loaded and running).
agent_unit_active() { # <id>
    systemctl --user is-active -q "$(quadlet_unit "$1").service" 2>/dev/null
}

# Prints Result, ExecMainCode and ExecMainStatus, one KEY=VALUE per line, for
# a unit that has already stopped.
agent_unit_props() { # <id>
    systemctl --user show "$(quadlet_unit "$1").service" -p Result -p ExecMainCode -p ExecMainStatus
}

# Maps one stopped unit's systemd state to an outcome. elapsed/deadline are
# wall-clock seconds that agent-run measures itself around `systemctl start
# --wait`, not a systemd property: RuntimeMaxSec's own Result on expiry is
# ambiguous with a clean exit (both can read Result=success) unless
# TimeoutStopSec *also* elapses, so a deadline hit is judged by elapsed time,
# not by string-matching Result. oom-kill is unambiguous and systemd sets it
# whenever the kernel OOM-killed a process in the unit's cgroup, regardless of
# OOMPolicy, so it is trusted directly and takes priority over a
# same-instant deadline reading.
classify_agent_outcome() { # <result> <exec-main-code> <exec-main-status> <elapsed-sec> <deadline-sec> <stop-requested 0|1>
    result=$1 code=$2 status=$3 elapsed=$4 deadline=$5 stop_requested=$6
    if [ "$result" = "oom-kill" ]; then
        echo "failed:oom"
        return
    fi
    if [ "$deadline" -gt 0 ] && [ "$elapsed" -ge "$deadline" ]; then
        echo "failed:timeout"
        return
    fi
    if [ "$stop_requested" -eq 1 ]; then
        echo "stopped"
        return
    fi
    if [ "$result" = "success" ] && [ "$code" = "exited" ] && [ "$status" = "0" ]; then
        echo "finished"
        return
    fi
    if [ "$code" = "killed" ]; then
        echo "failed:signal:$status"
        return
    fi
    echo "failed:exit:$status"
}
