# Shared by scripts/agent-run and scripts/agent-status: Quadlet unit naming,
# rendering, and the systemd-state-to-outcome mapping. Pure functions only
# (stdout in, stdout out; the two systemctl calls are confined to
# agent_unit_active and agent_unit_props), so scripts/agent-quadlet.test.sh can
# source this file and check it without podman or a systemd --user session.
#
# Placement: $XDG_RUNTIME_DIR/containers/systemd/, not the persistent
# $XDG_CONFIG_HOME one. Quadlet documents the runtime-dir path as the one for
# temporary units; a run's unit belongs there since agent-run deletes it
# itself once the run ends, and a crash before cleanup still self-clears at
# the next reboot instead of accumulating in persistent config.

quadlet_dir() {
    printf '%s/containers/systemd\n' "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
}

quadlet_unit() { # <id> -> unit name, without .container/.service
    printf 'agent-%s\n' "$1"
}

# Renders the .container Quadlet unit for one run to stdout.
#
# Volumes/environment/secret are passed pre-built (one directive per line, or
# empty) since what they contain depends on the harness and on agent-run's
# own environment, which this function does not read. Memory, CPU and tasks
# are systemd resource control, not Podman flags: RuntimeMaxSec is what makes
# the wall-time deadline a systemd job rather than something agent-run
# polls for.
render_agent_unit() { # <id> <image> <exec> <volumes> <environment> <secret> <cpu-quota-pct> <deadline-sec> <stop-grace-sec>
    id=$1 image=$2 exec=$3 volumes=$4 environment=$5 secret=$6 cpu_quota=$7 deadline=$8 stop_grace=$9
    printf '# Generated by scripts/agent-run for run %s; do not edit by hand.\n' "$id"
    printf '[Unit]\n'
    printf 'Description=agent sandbox run %s\n' "$id"
    printf '\n[Container]\n'
    printf 'Image=%s\n' "$image"
    printf 'Pull=never\n'
    printf 'ContainerName=%s\n' "$(quadlet_unit "$id")"
    printf 'UserNS=keep-id\n'
    printf '%s\n' "$volumes"
    [ -n "$environment" ] && printf '%s\n' "$environment"
    [ -n "$secret" ] && printf '%s\n' "$secret"
    printf 'Exec=%s\n' "$exec"
    printf '\n[Service]\n'
    # No automatic restart: a failed or timed-out run is not retried.
    printf 'Restart=no\n'
    printf 'MemoryMax=16G\n'
    # Without a swap cap, a run can exceed MemoryMax by spilling into the
    # host's swap (observed during the bounded host OOM smoke test).
    printf 'MemorySwapMax=0\n'
    printf 'CPUQuota=%s%%\n' "$cpu_quota"
    printf 'TasksMax=4096\n'
    printf 'RuntimeMaxSec=%s\n' "$deadline"
    printf 'TimeoutStopSec=%s\n' "$stop_grace"
    printf 'OOMPolicy=kill\n'
}

# True if the run's unit is currently active (loaded and running).
agent_unit_active() { # <id>
    systemctl --user is-active -q "$(quadlet_unit "$1").service" 2>/dev/null
}

# Prints Result, ExecMainCode and ExecMainStatus, one KEY=VALUE per line, for
# a unit that has already stopped.
agent_unit_props() { # <id>
    systemctl --user show "$(quadlet_unit "$1").service" -p Result -p ExecMainCode -p ExecMainStatus
}

# Map one stopped unit's actual systemd result to a manifest outcome. The
# host smoke test observes Result=timeout for RuntimeMaxSec expiry, even when
# the unit's stop grace also expires; timing `systemctl start --wait` includes
# container startup and would incorrectly mark a fast clean exit as timeout.
# systemctl show uses numeric wait(2) codes: 1=CLD_EXITED, 2=CLD_KILLED,
# 3=CLD_DUMPED. A very short successful Quadlet unit may already have reset
# ExecMainCode to 0 by the time --wait returns; Result=success and status=0
# remain authoritative in that case.
classify_agent_outcome() { # <result> <exec-main-code> <exec-main-status> <stop-requested 0|1>
    result=$1 code=$2 status=$3 stop_requested=$4
    if [ -z "$result" ] || [ -z "$code" ] || [ -z "$status" ]; then
        echo "failed:unit-state-unavailable"
        return
    fi
    if [ "$result" = "oom-kill" ]; then
        echo "failed:oom"
        return
    fi
    if [ "$stop_requested" -eq 1 ]; then
        case "$result" in
            timeout) echo "stopped:timeout" ;;
            exit-code) echo "failed:exit:$status" ;;
            *) echo "stopped" ;;
        esac
        return
    fi
    if [ "$result" = "timeout" ]; then
        echo "failed:timeout"
        return
    fi
    if [ "$result" = "success" ] && [ "$status" = "0" ] && { [ "$code" = "0" ] || [ "$code" = "1" ]; }; then
        echo "finished"
        return
    fi
    if [ "$code" = "2" ] || [ "$code" = "3" ]; then
        echo "failed:signal:$status"
        return
    fi
    echo "failed:exit:$status"
}
